const registerEvents = {
  onAbort: ['abort'],
  onAbortCapture: ['abort'],
  onAuxClick: ['auxclick'],
  onAuxClickCapture: ['auxclick'],
  onCancel: ['cancel'],
  onCancelCapture: ['cancel'],
  onCanPlay: ['canplay'],
  onCanPlayCapture: ['canplay'],
  onCanPlayThrough: ['canplaythrough'],
  onCanPlayThroughCapture: ['canplaythrough'],
  onClick: ['click'],
  onClickCapture: ['click'],
  onClose: ['close'],
  onCloseCapture: ['close'],
  onCopy: ['copy'],
  onCopyCapture: ['copy'],
  onCut: ['cut'],
  onCutCapture: ['cut'],
  onDrag: ['drag'],
  onDragCapture: ['drag'],
  onDragEnd: ['dragend'],
  onDragEndCapture: ['dragend'],
  onDragEnter: ['dragenter'],
  onDragEnterCapture: ['dragenter'],
  onDragExit: ['dragexit'],
  onDragExitCapture: ['dragexit'],
  onDragLeave: ['dragleave'],
  onDragLeaveCapture: ['dragleave'],
  onDragOver: ['dragover'],
  onDragOverCapture: ['dragover'],
  onDragStart: ['dragstart'],
  onDragStartCapture: ['dragstart'],
  onDrop: ['drop'],
  onDropCapture: ['drop'],
  onDurationChange: ['durationchange'],
  onDurationChangeCapture: ['durationchange'],
  onEmptied: ['emptied'],
  onEmptiedCapture: ['emptied'],
  onEncrypted: ['encrypted'],
  onEncryptedCapture: ['encrypted'],
  onEnded: ['ended'],
  onEndedCapture: ['ended'],
  onError: ['error'],
  onErrorCapture: ['error'],
  onGotPointerCapture: ['gotpointercapture'],
  onGotPointerCaptureCapture: ['gotpointercapture'],
  onInput: ['input'],
  onInputCapture: ['input'],
  onInvalid: ['invalid'],
  onInvalidCapture: ['invalid'],
  onKeyDown: ['keydown'],
  onKeyDownCapture: ['keydown'],
  onKeyPress: ['keypress'],
  onKeyPressCapture: ['keypress'],
  onKeyUp: ['keyup'],
  onKeyUpCapture: ['keyup'],
  onLoad: ['load'],
  onLoadCapture: ['load'],
  onLoadedData: ['loadeddata'],
  onLoadedDataCapture: ['loadeddata'],
  onLoadedMetadata: ['loadedmetadata'],
  onLoadedMetadataCapture: ['loadedmetadata'],
  onLoadStart: ['loadstart'],
  onLoadStartCapture: ['loadstart'],
  onLostPointerCapture: ['lostpointercapture'],
  onLostPointerCaptureCapture: ['lostpointercapture'],
  onMouseDown: ['mousedown'],
  onMouseDownCapture: ['mousedown'],
  onMouseMove: ['mousemove'],
  onMouseMoveCapture: ['mousemove'],
  onMouseOut: ['mouseout'],
  onMouseOutCapture: ['mouseout'],
  onMouseOver: ['mouseover'],
  onMouseOverCapture: ['mouseover'],
  onMouseUp: ['mouseup'],
  onMouseUpCapture: ['mouseup'],
  onPaste: ['paste'],
  onPasteCapture: ['paste'],
  onPause: ['pause'],
  onPauseCapture: ['pause'],
  onPlay: ['play'],
  onPlayCapture: ['play'],
  onPlaying: ['playing'],
  onPlayingCapture: ['playing'],
  onPointerCancel: ['pointercancel'],
  onPointerCancelCapture: ['pointercancel'],
  onPointerDown: ['pointerdown'],
  onPointerDownCapture: ['pointerdown'],
  onPointerMove: ['pointermove'],
  onPointerMoveCapture: ['pointermove'],
  onPointerOut: ['pointerout'],
  onPointerOutCapture: ['pointerout'],
  onPointerOver: ['pointerover'],
  onPointerOverCapture: ['pointerover'],
  onPointerUp: ['pointerup'],
  onPointerUpCapture: ['pointerup'],
  onProgress: ['progress'],
  onProgressCapture: ['progress'],
  onRateChange: ['ratechange'],
  onRateChangeCapture: ['ratechange'],
  onReset: ['reset'],
  onResetCapture: ['reset'],
  onSeeked: ['seeked'],
  onSeekedCapture: ['seeked'],
  onSeeking: ['seeking'],
  onSeekingCapture: ['seeking'],
  onStalled: ['stalled'],
  onStalledCapture: ['stalled'],
  onSubmit: ['submit'],
  onSubmitCapture: ['submit'],
  onSuspend: ['suspend'],
  onSuspendCapture: ['suspend'],
  onTimeUpdate: ['timeupdate'],
  onTimeUpdateCapture: ['timeupdate'],
  onTouchCancel: ['touchcancel'],
  onTouchCancelCapture: ['touchcancel'],
  onTouchEnd: ['touchend'],
  onTouchEndCapture: ['touchend'],
  onTouchStart: ['touchstart'],
  onTouchStartCapture: ['touchstart'],
  onVolumeChange: ['volumechange'],
  onVolumeChangeCapture: ['volumechange'],
  onScroll: ['scroll'],
  onScrollCapture: ['scroll'],
  onToggle: ['toggle'],
  onToggleCapture: ['toggle'],
  onTouchMove: ['touchmove'],
  onTouchMoveCapture: ['touchmove'],
  onWaiting: ['waiting'],
  onWaitingCapture: ['waiting'],
  onWheel: ['wheel'],
  onWheelCapture: ['wheel'],
  onAnimationEnd: ['animationend'],
  onAnimationEndCapture: ['animationend'],
  onAnimationIteration: ['animationiteration'],
  onAnimationIterationCapture: ['animationiteration'],
  onAnimationStart: ['animationstart'],
  onAnimationStartCapture: ['animationstart'],
  onDoubleClick: ['dblclick'],
  onDoubleClickCapture: ['dblclick'],
  onFocus: ['focusin'],
  onFocusCapture: ['focusin'],
  onBlur: ['focusout'],
  onBlurCapture: ['focusout'],
  onTransitionEnd: ['transitionend'],
  onTransitionEndCapture: ['transitionend'],
  onMouseEnter: ['mouseout', 'mouseover'],
  onMouseLeave: ['mouseout', 'mouseover'],
  onPointerEnter: ['pointerout', 'pointerover'],
  onPointerLeave: ['pointerout', 'pointerover'],
  onChange: [
    'change',
    'click',
    'focusin',
    'focusout',
    'input',
    'keydown',
    'keyup',
    'selectionchange',
  ],
  onChangeCapture: [
    'change',
    'click',
    'focusin',
    'focusout',
    'input',
    'keydown',
    'keyup',
    'selectionchange',
  ],
  onSelect: [
    'focusout',
    'contextmenu',
    'dragend',
    'focusin',
    'keydown',
    'keyup',
    'mousedown',
    'mouseup',
    'selectionchange',
  ],
  onSelectCapture: [
    'focusout',
    'contextmenu',
    'dragend',
    'focusin',
    'keydown',
    'keyup',
    'mousedown',
    'mouseup',
    'selectionchange',
  ],
  onBeforeInput: ['compositionend', 'keypress', 'textInput', 'paste'],
  onBeforeInputCapture: ['compositionend', 'keypress', 'textInput', 'paste'],
  onCompositionEnd: [
    'compositionend',
    'focusout',
    'keydown',
    'keypress',
    'keyup',
    'mousedown',
  ],
  onCompositionEndCapture: [
    'compositionend',
    'focusout',
    'keydown',
    'keypress',
    'keyup',
    'mousedown',
  ],
  onCompositionStart: [
    'compositionstart',
    'focusout',
    'keydown',
    'keypress',
    'keyup',
    'mousedown',
  ],
  onCompositionStartCapture: [
    'compositionstart',
    'focusout',
    'keydown',
    'keypress',
    'keyup',
    'mousedown',
  ],
  onCompositionUpdate: [
    'compositionupdate',
    'focusout',
    'keydown',
    'keypress',
    'keyup',
    'mousedown',
  ],
  onCompositionUpdateCapture: [
    'compositionupdate',
    'focusout',
    'keydown',
    'keypress',
    'keyup',
    'mousedown',
  ],
}

export default registerEvents
